### ISSUE TITLE
外接显示器无法检测

### ISSUE THREAD

**Issue by QingHui653** [a328661276/Clevo-NH50-NH70-Hackintosh-macOS10.15.4#2]
使用此EFI在 Z7M CT5NA,目前能正常运行. 主要是外接显示器无法检测
[黑果外接显示器](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html)
这个能集成到 EFI中吗?

**Comment by a328661276** [comment]
笔记本后边的HDMI和Type-C接口是走独立显卡的 当然没办法输出 可以插笔记本右边的MiniDP接口 是通集成显卡
如果显示器有DP接口 就买MiniDP转DP的线（亲测）
如果只有HDMI接口 那就买MiniDP转HDMI的线（未尝试过）

**Comment by QingHui653** [comment]
使用 miniDP转 VGA的线,不行.显示器只支持 VGA
